### ISSUE TITLE
Not connect in mongo

### ISSUE THREAD

**Issue by jay-ox** [jackysolanki007/dockerize-mongodb-replicaset#1]
Two issue is there 

1) After docker-compose up this command "docker exec mongo1 /data/rs-init.sh" is not running facing an error like "OCI runtime exec failed: exec failed: unable to start container process: exec: "/data/rs-init.sh": permission denied: unknown" i'm run this command using root user  in /data/mongo/ folder rs-init.sh is created as folder not script.

2) mongo is connect in local using the mongo-compass

**Comment by jackysolanki007** [comment]
Hii Jay,
1. from this error i think your container is not started,please check all container are running or not `docker ps -a '
2. yes mongodb connect in compass also

**Comment by jay-ox** [comment]
Hello,

actually i've bit confusion regarding the doc,
in 1st clone the repo, 
in 2nd create docker network,
in 3rd generate the key file and
in 4th verify the container so in between that there is no command to up the docker compose before that how can we verify that container will run
in 5th run the command to execute the rs-init.sh so it will create automatically ? because when we run this command it is created the directory and the file is not present in /data/mongo folder

so there is query in 4th and 5th option as well facing an issue while connect in mongo compass showing timeout, i'm using the linux ubuntu-20 version.

**Comment by jackysolanki007** [comment]
yes, after 2nd stage you have to run "docker-compose up -d",
the after you have to check container is running or not using "docker ps",
after all container are up and working then you have to run command 4.
I have update rs.init.sh file, please take a pull and start all process.

**Comment by jay-ox** [comment]
after docker-compose up -d and docker exec mongo1 /data/rs-init.sh run command facing below error, all container are running while check docker ps (mongo1, mongo2, mongo3)

"OCI runtime exec failed: exec failed: unable to start container process: exec: "/data/rs-init.sh": permission denied: unknown"

--> permission for folders

drwxrwxr-x 6 root             root 4096 Jun 16 20:29 ./
drwxrwxr-x 4 root             root 4096 Jun 16 20:29 ../
drwxrwxr-x 3 root             root 4096 Jun 16 20:30 mongo/
drwxrwxr-x 4 systemd-coredump root 4096 Jun 16 20:35 mongo1/
drwxrwxr-x 4 systemd-coredump root 4096 Jun 16 20:35 mongo2/
drwxrwxr-x 4 systemd-coredump root 4096 Jun 16 20:35 mongo3/


--> permission folder of mongo


drwxrwxr-x 3 root             root             4096 Jun 16 20:30 ./
drwxrwxr-x 6 root             root             4096 Jun 16 20:29 ../
-r-------- 1 systemd-coredump systemd-coredump 1040 Jun 16 20:32 mongo.keyfile
drwxr-xr-x 2 root             root             4096 Jun 16 20:30 rs-init.sh/
-rwxrwxr-x 1 root             root              499 Jun 16 20:29 rs.init.sh*

**Comment by jackysolanki007** [comment]
can you please delete all the things, and start again from fresh,
i've triad and tested in my local and it's working fine,
and next time please also put docker ps command output and logs of mongo1 container it might help.

**Comment by jay-ox** [comment]
ya i tried in fresh setup but don't know what is the issue same error comes can you share mail id so i can share the snapshot over there.

**Comment by jackysolanki007** [comment]
you can also add screenshot here, as i tell you that please show output of , "docker ps" command, and show logs from mongo1 container.

**Comment by jay-ox** [comment]
> you can also add screenshot here, as i tell you that please show output of , "docker ps" command, and show logs from mongo1 container.

**Comment by jay-ox** [comment]
ok i attach snapshot as well as the logs

[mongo1.txt](https://github.com/jackysolanki007/dockerize-mongodb-replicaset/files/11798519/mongo1.txt)

![2023-06-20_15-07](https://github.com/jackysolanki007/dockerize-mongodb-replicaset/assets/108863714/b45dd1cc-4cdf-4fa0-a4c8-8342282a9a25)

**Comment by jackysolanki007** [comment]
ok i got this why this happen, you have to first remove rs-init.sh/ folder and then also remove mongo1,mongo2,mongo3 folder and then re-create it, then it might helps you in that case.

**Comment by jay-ox** [comment]
yes,deleted the all mongo folder except mongo but don't know still facing the same issue and folder is automatically created while run command "sudo docker exec mongo1 /data/rs-init.sh"  rs-init.sh folder is created

docker are running but not connect in mongo compass as well this above command is not running, actually your docker-compose is perfect for our requirement we want to implement this in production, once it run in local.

**Comment by jackysolanki007** [comment]
okay, let me tell you basic of docker, when docker can't find file it will try to create a volume.
i will give you one another way to check inside docker container.
1. go inside mongo1 container using :  `docker exec -it mongo1 /bin/bash`
2. then go to directory data using `cd /data/`
3. and check that file is there or not using `ls -al`
4. and if file are there use command this command to execute that file: `sh rs-init.sh`

i would be happy if you implement in your production server.

**Comment by jackysolanki007** [comment]
it's mistake from my end,
i've pushed the wrong file name `rs.init.sh`,
now i've rename it with proper `rs-init.sh`, please clone again and try this time it should be work.

**Comment by jay-ox** [comment]
yes docker is working now but still issue with connect in mongo, thanks for the reply time to time

i will check with monog compass issue and update if find any issue.

thanks
